### ISSUE TITLE
Package needs to be split into 2 or more

### ISSUE THREAD

**Issue by tarikjn** [tiendungkid/uppromote-hydrogen#2]
This package needs to be split into a core package that does NOT connect to the Shopify API, and just receive and returns back the data needed -- then you can supply another one connecting it with the API/Hydrogen.

We're trying to integrate UpPromote with a custom headless store that uses relay (and is generates a static site) and it's a mess trying to figure out exactly what UpPromote needs to function and how to integrate it.

Is there **technical** documentation anywhere about this? i.e. _make this cookie if you receive the `sca_ref` keyword_, _store this attribute to createCart_.

**Comment by tiendungkid** [comment]
Hi tirakjn

I'm Anthony from UpPromote.

Looks like you are using the wrong old version of this package.

Currently, you have to install this package in npmjs at this link: https://www.npmjs.com/package/@secomus/uppromote-hydrogen

Regarding the question of why we don't divide it into multiple packages because:
- We require the @shopify/hydrogen package to work
- This package helps us track customer orders through shopping cart data (@shopify/hydrogen)
Sorry for the inconvenience. This year we are trying to find new tracking methods to suit all types of websites

**Comment by tiendungkid** [comment]
Thank you for your goodwill! Our package is currently in private mode. Could you mind sending me more details about the issue that you found? 
Please kindly report that right under this thread or send via email address: support@secomapp.com (with hashtag #UpPromote in the email body).
My apologize for this inconvenience and hope to see your reply soon!
